server:
  port: 8090
spring:
  data:
    mongodb:
      username: e_commerce_app
      password: ZX9GoDUf
      host: localhost
      port: 27017
      database: customer
      authentication-database: admin
